export const smartLearnAppearance = {
  layout: {
    logoImageUrl: "/smartlearn-logo.svg",
    logoLinkUrl: "/",
    logoPlacement: "inside",
    socialButtonsPlacement: "bottom",
    socialButtonsVariant: "blockButton",
    termsPageUrl: undefined,
    privacyPageUrl: undefined,
    helpPageUrl: undefined,
    showOptionalFields: true,
    animations: true,
  },
  variables: {
    colorPrimary: "#4F46E5",
    colorBackground: "#ffffff",
    colorText: "#0f172a",
    colorTextSecondary: "#64748b",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
  },
  elements: {
    rootBox: "mx-auto",
    card: "shadow-xl border border-slate-200",
    headerTitle: "text-slate-900 font-bold",
    headerSubtitle: "text-slate-500",
    socialButtonsBlockButton: "border-slate-200",
    formButtonPrimary:
      "bg-indigo-600 hover:bg-indigo-500 text-sm font-semibold shadow-md shadow-indigo-600/20",
    footer: "hidden",
    footerAction: "hidden",
    identityPreviewEditButton: "text-indigo-600",
    formFieldInput: "rounded-xl border-slate-200",
    otpCodeFieldInput: "border-slate-200",
    badge: "bg-indigo-50 text-indigo-700",
    logoBox: "h-12 justify-center",
    logoImage: "h-12 w-12",
  },
};
