/** Class 12 Maths Ch1 — Relations and Functions (100 board MCQs from CSV) */
export const MATHS_12_CH1_RF = [
  {
    prompt: "A relation R on set A = {1, 2, 3} is defined as R = {(1,1), (2,2), (3,3), (1,2), (2,1)}. What type of relation is R?",
    options: [
      "Only reflexive",
      "Reflexive and symmetric",
      "Reflexive, symmetric and transitive",
      "Equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A relation R on set A is reflexive if:",
    options: [
      "(a,b) ∈ R for all a,b ∈ A",
      "(a,a) ∈ R for all a ∈ A",
      "(a,b) ∈ R implies (b,a) ∈ R",
      "(a,b) ∈ R and (b,c) ∈ R implies (a,c) ∈ R",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A relation R on set A is symmetric if:",
    options: [
      "(a,a) ∈ R for all a ∈ A",
      "(a,b) ∈ R implies (b,a) ∈ R",
      "(a,b) ∈ R and (b,c) ∈ R implies (a,c) ∈ R",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A relation R on set A is transitive if:",
    options: [
      "(a,a) ∈ R for all a ∈ A",
      "(a,b) ∈ R implies (b,a) ∈ R",
      "(a,b) ∈ R and (b,c) ∈ R implies (a,c) ∈ R",
      "All of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R = {(1,1), (2,2), (3,3)} on A = {1, 2, 3}, then R is:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "An equivalence relation",
      "Transitive only",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The smallest equivalence relation on set A = {1, 2} is:",
    options: [
      "{(1,1)}",
      "{(1,1), (2,2)}",
      "{(1,2), (2,1)}",
      "{(1,1), (2,2), (1,2)}",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The number of reflexive relations on a set with n elements is:",
    options: [
      "2^(n²)",
      "2^(n(n-1))",
      "2^(n(n+1))",
      "n²",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The number of symmetric relations on a set with n elements is:",
    options: [
      "2^(n²)",
      "2^(n(n-1)/2)",
      "2^(n(n+1)/2)",
      "2^n",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If a relation is reflexive, symmetric and transitive, it is called:",
    options: [
      "Partial order",
      "Equivalence relation",
      "Total order",
      "Function",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'is congruent to' on the set of triangles is:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "Transitive only",
      "An equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'is parallel to' on the set of lines in a plane is:",
    options: [
      "Reflexive and symmetric",
      "Symmetric and transitive",
      "Reflexive, symmetric and transitive",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'is perpendicular to' on the set of lines in a plane is:",
    options: [
      "Reflexive",
      "Symmetric",
      "Transitive",
      "Equivalence",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R is an equivalence relation on set A, then the equivalence class of a ∈ A is:",
    options: [
      "{b ∈ A : (a,b) ∈ R}",
      "{b ∈ A : (b,a) ∈ R}",
      "{a ∈ A : (a,a) ∈ R}",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'has the same number of pages' on the set of books is:",
    options: [
      "Only reflexive",
      "Only symmetric",
      "Only transitive",
      "An equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R = {(a,b): a ≤ b} on set of real numbers, then R is:",
    options: [
      "Reflexive and symmetric",
      "Reflexive and transitive",
      "Symmetric and transitive",
      "Equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation R on N defined by R = {(a,b): a divides b} is:",
    options: [
      "Reflexive and symmetric",
      "Reflexive and transitive",
      "Symmetric and transitive",
      "Equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R and S are equivalence relations on set A, then R ∩ S is:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "An equivalence relation",
      "Transitive only",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'is a friend of' on the set of people is:",
    options: [
      "Reflexive",
      "Symmetric",
      "Transitive",
      "Equivalence",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The identity relation on set A is always:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "An equivalence relation",
      "Transitive only",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R is a relation on A = {1,2,3} given by R = {(1,1), (2,2), (3,3), (1,2), (2,3)}, then R is:",
    options: [
      "Reflexive",
      "Symmetric",
      "Transitive",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The universal relation on a non-empty set A is:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "An equivalence relation",
      "Transitive only",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The void relation on a non-empty set A is:",
    options: [
      "Reflexive",
      "Symmetric",
      "Transitive",
      "Symmetric and transitive",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If R = {(a,b): a-b is divisible by 3} on Z, then R is:",
    options: [
      "Reflexive only",
      "Symmetric only",
      "Transitive only",
      "An equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The relation 'is a subset of' (⊆) on the power set of A is:",
    options: [
      "Reflexive and symmetric",
      "Reflexive and transitive",
      "Symmetric and transitive",
      "Equivalence relation",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The number of relations on a set with 3 elements is:",
    options: [
      "8",
      "64",
      "512",
      "1024",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A function f: A → B is injective (one-one) if:",
    options: [
      "f(a) = f(b) implies a = b",
      "f(a) ≠ f(b) for all a ≠ b",
      "Both A and B",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A function f: A → B is surjective (onto) if:",
    options: [
      "Every element of A has an image in B",
      "Every element of B has a pre-image in A",
      "f is one-one",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A function which is both injective and surjective is called:",
    options: [
      "Identity function",
      "Constant function",
      "Bijective function",
      "Inverse function",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = 2x + 3 is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = x² is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: N → N defined by f(x) = x + 1 is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = x³ is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R⁺ defined by f(x) = eˣ is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = |x| is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = sin x is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: [0, π/2] → [0, 1] defined by f(x) = sin x is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = 3x - 5 is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B is injective, then:",
    options: [
      "n(A) ≤ n(B)",
      "n(A) ≥ n(B)",
      "n(A) = n(B)",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B is surjective, then:",
    options: [
      "n(A) ≤ n(B)",
      "n(A) ≥ n(B)",
      "n(A) = n(B)",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B is bijective and A is finite, then:",
    options: [
      "n(A) < n(B)",
      "n(A) > n(B)",
      "n(A) = n(B)",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: Z → Z defined by f(x) = x + 2 is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = [x] (greatest integer function) is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = x³ + 1 is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: N → N defined by f(n) = n² is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = 5 is:",
    options: [
      "One-one and onto",
      "One-one but not onto",
      "Onto but not one-one",
      "Neither one-one nor onto",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R → R defined by f(x) = ax + b (a ≠ 0) is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f: R⁺ → R⁺ defined by f(x) = 1/x is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B and g: B → C are both injective, then gof is:",
    options: [
      "Injective",
      "Surjective",
      "Bijective",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B and g: B → C are both surjective, then gof is:",
    options: [
      "Injective",
      "Surjective",
      "Bijective",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B and g: B → C are both bijective, then gof is:",
    options: [
      "Injective",
      "Surjective",
      "Bijective",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B and g: B → C, then gof: A → C is defined as:",
    options: [
      "gof(x) = g(f(x))",
      "gof(x) = f(g(x))",
      "gof(x) = f(x) · g(x)",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 2x + 1 and g(x) = x², then gof(x) =",
    options: [
      "(2x+1)²",
      "2x² + 1",
      "4x² + 1",
      "2x² + 4x + 1",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 2x + 1 and g(x) = x², then fog(x) =",
    options: [
      "(2x+1)²",
      "2x² + 1",
      "4x² + 1",
      "2x² + 4x + 1",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x + 1 and g(x) = 2x, then gof(3) =",
    options: [
      "6",
      "7",
      "8",
      "9",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x² and g(x) = x + 1, then fog(2) =",
    options: [
      "3",
      "4",
      "5",
      "9",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "Composition of functions is:",
    options: [
      "Commutative",
      "Associative",
      "Both commutative and associative",
      "Neither commutative nor associative",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: R → R, f(x) = 2x and g: R → R, g(x) = x/2, then gof(x) =",
    options: [
      "x",
      "x/4",
      "4x",
      "2x",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x + 2 and g(x) = x - 2, then gof(x) =",
    options: [
      "x",
      "x + 4",
      "x - 4",
      "0",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 3x and g(x) = x + 1, then fog(1) =",
    options: [
      "3",
      "4",
      "6",
      "7",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B, g: B → C, h: C → D, then ho(gof) =",
    options: [
      "(hog)of",
      "fo(goh)",
      "go(hof)",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x² + 1 and g(x) = √x, then gof(x) (for x ≥ 0) =",
    options: [
      "x² + 1",
      "√(x²+1)",
      "x + 1",
      "√x + 1",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = sin x and g(x) = x², then gof(x) =",
    options: [
      "sin(x²)",
      "(sin x)²",
      "sin²x",
      "Both B and C",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = log x and g(x) = eˣ, then fog(x) =",
    options: [
      "x",
      "e^(log x)",
      "log(eˣ)",
      "Both A and C",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 1/x and g(x) = 1/x, then gof(x) =",
    options: [
      "1/x",
      "x",
      "x²",
      "1/x²",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x + 3 and g(x) = 2x - 1, then fog(x) =",
    options: [
      "2x + 2",
      "2x + 5",
      "2x - 1",
      "2x + 3",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A function f: A → B is invertible if and only if f is:",
    options: [
      "Injective",
      "Surjective",
      "Bijective",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: A → B is invertible, then f⁻¹: B → A satisfies:",
    options: [
      "f⁻¹of = I_A and fof⁻¹ = I_B",
      "f⁻¹of = I_B and fof⁻¹ = I_A",
      "f⁻¹of = f",
      "fof⁻¹ = f",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 2x + 3, then f⁻¹(x) =",
    options: [
      "(x-3)/2",
      "(x+3)/2",
      "2x - 3",
      "x/2 - 3",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x³, then f⁻¹(x) =",
    options: [
      "x^(1/3)",
      "x³",
      "1/x³",
      "-x³",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = (2x+1)/(x-3), then f⁻¹(x) =",
    options: [
      "(3x+1)/(x-2)",
      "(3x-1)/(x+2)",
      "(3x+1)/(x+2)",
      "(3x-1)/(x-2)",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: R → R, f(x) = 3x - 5, then f⁻¹(4) =",
    options: [
      "3",
      "4",
      "5",
      "6",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = eˣ, then f⁻¹(x) =",
    options: [
      "log x",
      "e^(-x)",
      "1/eˣ",
      "x",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = log x, then f⁻¹(x) =",
    options: [
      "eˣ",
      "1/log x",
      "10ˣ",
      "x",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x + 2 and g(x) = x - 2, then (gof)⁻¹(x) =",
    options: [
      "x",
      "x + 4",
      "x - 4",
      "Does not exist",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f is invertible, then (f⁻¹)⁻¹ =",
    options: [
      "f",
      "f⁻¹",
      "I",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 5x + 2, then f⁻¹(7) =",
    options: [
      "1",
      "2",
      "3",
      "4",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: [0,∞) → [0,∞), f(x) = x², then f⁻¹(x) =",
    options: [
      "√x",
      "x²",
      "-√x",
      "1/x²",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = (x+1)/(x-1), then f⁻¹(x) =",
    options: [
      "(x+1)/(x-1)",
      "(x-1)/(x+1)",
      "(1+x)/(x-1)",
      "(x+1)/(1-x)",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 2x - 1, then f⁻¹(f(3)) =",
    options: [
      "1",
      "2",
      "3",
      "4",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x/(x+1), then f⁻¹(x) =",
    options: [
      "x/(1-x)",
      "(1-x)/x",
      "x/(x-1)",
      "(x+1)/x",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A binary operation * on set A is a function from:",
    options: [
      "A → A",
      "A × A → A",
      "A → A × A",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "Addition is a binary operation on:",
    options: [
      "N",
      "Z",
      "Q",
      "All of these",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "Subtraction is a binary operation on:",
    options: [
      "N",
      "Z",
      "Q",
      "Both B and C",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A binary operation * on A is commutative if:",
    options: [
      "a*b = b*a for all a,b ∈ A",
      "(a*b)*c = a*(b*c)",
      "a*e = a",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "A binary operation * on A is associative if:",
    options: [
      "a*b = b*a",
      "(a*b)*c = a*(b*c)",
      "a*e = a",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "An element e ∈ A is an identity element for * if:",
    options: [
      "a*e = a for all a ∈ A",
      "e*a = a for all a ∈ A",
      "Both A and B",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If e is identity for *, then a ∈ A has inverse b if:",
    options: [
      "a*b = e",
      "b*a = e",
      "Both A and B",
      "None of these",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The identity element for addition on R is:",
    options: [
      "0",
      "1",
      "-1",
      "None",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The identity element for multiplication on R is:",
    options: [
      "0",
      "1",
      "-1",
      "None",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If a*b = a + b + 1 on Z, the identity element is:",
    options: [
      "0",
      "1",
      "-1",
      "2",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x² and g(x) = √x, then fog(x) for x ≥ 0 is:",
    options: [
      "x",
      "x²",
      "√x",
      "|x|",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The domain of f(x) = 1/(x-2) is:",
    options: [
      "R",
      "R - {2}",
      "R - {0}",
      "[2, ∞)",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The range of f(x) = x² is:",
    options: [
      "R",
      "[0, ∞)",
      "(0, ∞)",
      "R - {0}",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The range of f(x) = sin x is:",
    options: [
      "[-1, 1]",
      "R",
      "[0, 1]",
      "[-1, 0]",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = x² - 4x + 5, the minimum value of f is:",
    options: [
      "0",
      "1",
      "2",
      "5",
    ] as [string, string, string, string],
    correctIndex: 1,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f: {1,2,3} → {a,b} is onto, then the number of such functions is:",
    options: [
      "6",
      "8",
      "4",
      "2",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The number of bijective functions from A to B where n(A) = n(B) = 3 is:",
    options: [
      "6",
      "9",
      "27",
      "81",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = 2x + 1 and g(x) = x - 3, then (f+g)(x) =",
    options: [
      "3x - 2",
      "3x + 4",
      "2x - 2",
      "x + 4",
    ] as [string, string, string, string],
    correctIndex: 0,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "The function f(x) = x|x| is:",
    options: [
      "One-one only",
      "Onto only",
      "Bijective",
      "Neither",
    ] as [string, string, string, string],
    correctIndex: 2,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  },
  {
    prompt: "If f(x) = [x] + [-x], where [.] is greatest integer function, then f(x) =",
    options: [
      "0 for all x",
      "-1 for non-integer x",
      "0 for integer x",
      "Both B and C",
    ] as [string, string, string, string],
    correctIndex: 3,
    explanation: "Class 12 Maths · Relations and Functions (board MCQ).",
  }
].map((q) => ({
  ...q,
  tags: [
    "relations",
    "functions",
    "relation",
    "function",
    "equivalence",
    "injective",
    "surjective",
    "bijective",
    "inverse",
    "binary",
    "maths",
    "mathematics",
    "class 12",
    "12-maths-ch1",
  ],
}));
